image: Visual Studio 2017
configuration: Release
version: '{build}'

install:
- ps: >-
    if ($env:APPVEYOR_REPO_TAG -eq "false")
    {
      $env:COMMIT_DESCRIPTION = git describe --tags
    }
    else
    {
      $env:COMMIT_DESCRIPTION = $env:APPVEYOR_REPO_TAG_NAME
    }
    Write-Host Build version is $env:COMMIT_DESCRIPTION

dotnet_csproj:
  patch: true
  file: 'Medium\Medium.csproj'
  version: $(commit_description)

before_build:
- cmd: dotnet restore

build:
  project: MediumSdk.sln

test_script:
  - cmd: dotnet test Medium.Tests/Medium.Tests.csproj

artifacts:
- path: '**/*.nupkg'
  name: Nuget Packages

deploy:
- provider: NuGet
  api_key:
    secure: y7n963kT1eor3dpj742k0mwnMPXsWGnljEGlfUr2zaGgqtMOJ4OegiWmLctuGYlY
  on:
    appveyor_repo_tag: true
